import {one,rows} from '../database/db';import {formatMoney} from '../utils/currency';import {monthBounds,localISODate} from '../utils/date';import {savingsProgress} from '../calculations/finance';
export type AssistantReply={intent:string;title:string;answer:string;details:string[]};
const money=(n:number,c='NGN')=>formatMoney(Number(n||0),c);
export const askFinancialAssistant=async(raw:string,currency='NGN'):Promise<AssistantReply>=>{const q=raw.trim().toLowerCase(),m=monthBounds(),last=monthBounds(-1);
 if(/afford|buy.*phone|can i buy/.test(q)){const amount=Number((q.match(/[\d,.]+/)?.[0]||'0').replace(/,/g,''));const bal=await one<any>('SELECT COALESCE(SUM(current_balance),0) v FROM accounts');const debt=await one<any>("SELECT COALESCE(SUM(minimum_payment),0) v FROM debts WHERE status IN ('active','overdue')");const exp=await one<any>("SELECT COALESCE(SUM(amount),0) v FROM transactions WHERE type='expense' AND date BETWEEN ? AND ?",[m.start,m.end]);const safe=Math.max(0,Number(bal?.v||0)-Number(debt?.v||0)-Number(exp?.v||0));return {intent:'affordability',title:'Affordability check',answer:amount>0&&safe>=amount?`Based on your recorded commitments, ${money(amount,currency)} fits inside your current uncommitted balance.`:`Your recorded uncommitted balance is about ${money(safe,currency)}, so this purchase would use more than that buffer.`,details:[`Current account balance: ${money(bal?.v,currency)}`,`Recorded monthly debt obligations: ${money(debt?.v,currency)}`,`Expenses this month: ${money(exp?.v,currency)}`,`Estimated uncommitted balance: ${money(safe,currency)}`]};}
 if(/food/.test(q)&&/spend|spent/.test(q)){const r=await one<any>("SELECT COALESCE(SUM(t.amount),0) v FROM transactions t JOIN categories c ON c.id=t.category_id WHERE t.type='expense' AND lower(c.name)='food' AND t.date BETWEEN ? AND ?",[m.start,m.end]);return {intent:'food_spend',title:'Food spending',answer:`You spent ${money(r?.v,currency)} on Food this month.`,details:[`${m.start} to ${m.end}`]};}
 if(/how much.*owe|debt/.test(q)&&!/clear/.test(q)){const r=await one<any>("SELECT COALESCE(SUM(current_balance),0) v FROM debts WHERE status!='paid'");return {intent:'debt_total',title:'Outstanding debt',answer:`Your recorded outstanding debt is ${money(r?.v,currency)}.`,details:[]};}
 if(/next.*debt|next.*payment/.test(q)){const r=await one<any>("SELECT lender_name,due_date,minimum_payment,currency FROM debts WHERE status IN ('active','overdue') ORDER BY due_date LIMIT 1");return r?{intent:'next_payment',title:'Next debt payment',answer:`${money(r.minimum_payment,r.currency)} to ${r.lender_name} is due on ${r.due_date}.`,details:[]}:{intent:'next_payment',title:'Next debt payment',answer:'You have no active debt payment recorded.',details:[]};}
 if(/goal|save each month/.test(q)){const r=await one<any>('SELECT * FROM savings_goals ORDER BY deadline LIMIT 1');if(!r)return {intent:'goal',title:'Savings goal',answer:'No savings goal is recorded yet.',details:[]};const p=savingsProgress(r.target_amount,r.current_amount,r.deadline);return {intent:'goal',title:r.name,answer:`Save about ${money(p.requiredMonthly,r.currency)} per month to reach the recorded deadline.`,details:[`${p.percentage.toFixed(1)}% complete`,`${money(p.remaining,r.currency)} remaining`,`Deadline: ${r.deadline}`]};}
 if(/category.*most|consumes most|biggest categor/.test(q)){const r=await one<any>("SELECT COALESCE(c.name,'Uncategorized') name,SUM(t.amount) v FROM transactions t LEFT JOIN categories c ON c.id=t.category_id WHERE t.type='expense' AND t.date BETWEEN ? AND ? GROUP BY c.name ORDER BY v DESC LIMIT 1",[m.start,m.end]);return r?{intent:'top_category',title:'Top spending category',answer:`${r.name} is your largest expense category this month at ${money(r.v,currency)}.`,details:[]}:{intent:'top_category',title:'Top spending category',answer:'No expenses are recorded this month.',details:[]};}
 if(/earn|income/.test(q)){const r=await one<any>("SELECT COALESCE(SUM(amount),0) v FROM transactions WHERE type='income' AND date BETWEEN ? AND ?",[m.start,m.end]);return {intent:'income',title:'Monthly income',answer:`You earned ${money(r?.v,currency)} this month.`,details:[]};}
 if(/last month/.test(q)&&/spend/.test(q)){const r=await one<any>("SELECT COALESCE(SUM(amount),0) v FROM transactions WHERE type='expense' AND date BETWEEN ? AND ?",[last.start,last.end]);return {intent:'last_month_expense',title:'Last month spending',answer:`You spent ${money(r?.v,currency)} last month.`,details:[`${last.start} to ${last.end}`]};}
 if(/biggest expense/.test(q)){const rs=await rows<any>("SELECT description,amount,currency,date FROM transactions WHERE type='expense' ORDER BY amount DESC LIMIT 5");return {intent:'biggest_expenses',title:'Biggest expenses',answer:rs.length?'Here are your largest recorded expenses.':'No expenses are recorded.',details:rs.map(r=>`${r.date}: ${r.description} — ${money(r.amount,r.currency)}`)};}
 return {intent:'help',title:'Finora Assistant',answer:'I can calculate affordability, monthly income or spending, food spending, total debt, next debt payment, savings requirements, top categories and biggest expenses from your local data.',details:['Try: “How much do I owe?”','Try: “How much did I spend on food this month?”','Try: “Can I afford a ₦100,000 phone?”']};};
