import {FileSystem,Dirs} from 'react-native-file-access';import Share from 'react-native-share';import {pick,keepLocalCopy} from '@react-native-documents/picker';import {execute,rows,getDb} from '../database/db';import {TABLES} from '../database/schema';import type {BackupEnvelope} from '../types/domain';import {recalculateAccountBalances} from './accountService';
const ALL_TABLES=['preferences',...TABLES] as const;
const checksum=(text:string)=>{let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');};
export const buildBackup=async():Promise<BackupEnvelope>=>{const data:Record<string,unknown[]>={},recordCounts:Record<string,number>={};for(const table of ALL_TABLES){const r=await rows<any>(`SELECT * FROM ${table}`);data[table]=r;recordCounts[table]=r.length;}const core={format:'finora-backup' as const,version:1 as const,appVersion:'1.0.0',createdAt:new Date().toISOString(),recordCounts,data};return {...core,checksum:checksum(JSON.stringify(core))};};
export const validateBackup=(value:any):BackupEnvelope=>{if(!value||value.format!=='finora-backup'||value.version!==1||!value.data||!value.recordCounts)throw new Error('This is not a supported Finora backup.');const {checksum:expected,...core}=value;if(checksum(JSON.stringify(core))!==expected)throw new Error('Backup checksum failed. The file may be incomplete or modified.');return value as BackupEnvelope;};
export const exportJsonBackup=async()=>{const backup=await buildBackup();const name=`finora-backup-${new Date().toISOString().slice(0,10)}.json`;const path=`${Dirs.DocumentDir}/${name}`;await FileSystem.writeFile(path,JSON.stringify(backup,null,2),'utf8');await Share.open({url:`file://${path}`,type:'application/json',filename:name,failOnCancel:false});return path;};
export const exportTransactionsCsv=async()=>{const tx=await rows<any>('SELECT * FROM transactions ORDER BY date,time');const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;const cols=['id','type','amount','currency','date','time','description','account_id','category_id','payment_method','notes','reference'];const csv=[cols.join(','),...tx.map(r=>cols.map(c=>q(r[c])).join(','))].join('\n');const name=`finora-transactions-${new Date().toISOString().slice(0,10)}.csv`,path=`${Dirs.DocumentDir}/${name}`;await FileSystem.writeFile(path,csv,'utf8');await Share.open({url:`file://${path}`,type:'text/csv',filename:name,failOnCancel:false});return path;};

export const exportHumanReadableReport=async()=>{const now=new Date(),month=now.toISOString().slice(0,7);const summary=await rows<any>(`SELECT COALESCE(SUM(CASE WHEN type IN ('income','loan_received') THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type IN ('expense','debt_repayment') THEN amount ELSE 0 END),0) expenses FROM transactions WHERE substr(date,1,7)=?`,[month]);const debt=await rows<any>("SELECT lender_name,current_balance,currency,due_date,status FROM debts WHERE status!='paid' ORDER BY due_date");const goals=await rows<any>('SELECT name,current_amount,target_amount,currency,deadline FROM savings_goals ORDER BY deadline');const a=summary[0]||{};const lines=['FINORA FINANCIAL REPORT',`Generated: ${new Date().toLocaleString()}`,`Period: ${month}`,'',`Income: ${Number(a.income||0).toFixed(2)}`,`Expenses: ${Number(a.expenses||0).toFixed(2)}`,`Net cash flow: ${(Number(a.income||0)-Number(a.expenses||0)).toFixed(2)}`,'','ACTIVE DEBTS',...debt.map(d=>`${d.lender_name}: ${d.currency} ${Number(d.current_balance).toFixed(2)} due ${d.due_date} (${d.status})`),'','SAVINGS GOALS',...goals.map(g=>`${g.name}: ${g.currency} ${Number(g.current_amount).toFixed(2)} / ${Number(g.target_amount).toFixed(2)} by ${g.deadline}`)];const name=`finora-report-${new Date().toISOString().slice(0,10)}.txt`,path=`${Dirs.DocumentDir}/${name}`;await FileSystem.writeFile(path,lines.join('\n'),'utf8');await Share.open({url:`file://${path}`,type:'text/plain',filename:name,failOnCancel:false});return path;};
export const pickBackup=async()=>{const [file]=await pick({type:'application/json'});const [copy]=await keepLocalCopy({files:[{uri:file.uri,fileName:file.name??'finora-backup.json'}],destination:'cachesDirectory'});if(copy.status!=='success')throw new Error(copy.copyError);const path=copy.localUri.replace(/^file:\/\//,'');const text=await FileSystem.readFile(path,'utf8');return validateBackup(JSON.parse(text));};
const deleteOrder=['transaction_tags','debt_payments','transactions','budget_categories','budgets','reminders','notifications','financial_events','recurring_transactions','savings_goals','debts','tags','categories','accounts','audit_logs','preferences'];
const insertRow=async(table:string,row:any,mode:'merge'|'replace')=>{const keys=Object.keys(row);if(!keys.length)return;const placeholders=keys.map(()=>'?').join(',');const verb=mode==='merge'?'INSERT OR IGNORE':'INSERT OR REPLACE';await execute(`${verb} INTO ${table}(${keys.join(',')}) VALUES(${placeholders})`,keys.map(k=>row[k]??null));};
export const restoreBackup=async(backup:BackupEnvelope,mode:'merge'|'replace')=>{validateBackup(backup);const db=getDb();await db.transaction(async tx=>{await tx.executeAsync('PRAGMA defer_foreign_keys=ON');if(mode==='replace')for(const table of deleteOrder)await tx.executeAsync(`DELETE FROM ${table}`);for(const table of ALL_TABLES){for(const row of backup.data[table]??[]){const keys=Object.keys(row as any);if(!keys.length)continue;const verb=mode==='merge'?'INSERT OR IGNORE':'INSERT OR REPLACE';await tx.executeAsync(`${verb} INTO ${table}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`,keys.map(k=>(row as any)[k]??null));}}});await recalculateAccountBalances();};
