import notifee,{AndroidImportance,AndroidNotificationSetting,RepeatFrequency,TriggerType,type TimestampTrigger} from '@notifee/react-native';
import {execute,one,rows} from '../database/db';import {uuid} from '../utils/id';import {formatMoney} from '../utils/currency';import {loadPreferences} from '../database/preferences';

export const FINORA_CHANNEL='finora-finance';
export const ensureNotificationChannel=async()=>notifee.createChannel({id:FINORA_CHANNEL,name:'Finora financial reminders',importance:AndroidImportance.HIGH,sound:'default',vibration:true});
export const requestNotificationPermission=async()=>{await notifee.requestPermission();await ensureNotificationChannel();return notifee.getNotificationSettings();};
export const exactAlarmAvailable=async()=>{const s=await notifee.getNotificationSettings();return s.android.alarm!==AndroidNotificationSetting.DISABLED;};
const repeatMap=(f?:string|null)=>f==='daily'?RepeatFrequency.DAILY:f==='weekly'?RepeatFrequency.WEEKLY:undefined;
const categoryAllowed=async(category:string)=>{const p=await loadPreferences();const map=p.notificationCategories||{debt:true,budget:true,savings:true,bill:true,custom:true};return p.notificationEnabled && (map as any)[category]!==false;};
const createTrigger=async(id:string,title:string,message:string,scheduledAt:string,repeatFrequency?:string|null)=>{const trigger:TimestampTrigger={type:TriggerType.TIMESTAMP,timestamp:new Date(scheduledAt).getTime(),alarmManager:{allowWhileIdle:true},...(repeatMap(repeatFrequency)?{repeatFrequency:repeatMap(repeatFrequency)}:{})};await notifee.createTriggerNotification({id,title,body:message,data:{category:'reminder'},android:{channelId:FINORA_CHANNEL,pressAction:{id:'default'},importance:AndroidImportance.HIGH}},trigger);};
export const scheduleLocalReminder=async(input:{id?:string;title:string;message:string;scheduledAt:string;category:string;entityId?:string|null;repeatFrequency?:string|null})=>{const date=new Date(input.scheduledAt);if(Number.isNaN(date.getTime()))throw new Error('Invalid reminder date.');if(date.getTime()<=Date.now())throw new Error('Reminder must be scheduled in the future.');await ensureNotificationChannel();const notificationId=input.id||uuid(),now=new Date().toISOString();if(await categoryAllowed(input.category))await createTrigger(notificationId,input.title,input.message,input.scheduledAt,input.repeatFrequency);await execute('INSERT OR REPLACE INTO reminders(id,title,message,scheduled_at,category,entity_id,repeat_frequency,enabled,notification_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[notificationId,input.title,input.message,input.scheduledAt,input.category,input.entityId??null,input.repeatFrequency??null,1,notificationId,now,now]);return notificationId;};
export const cancelReminder=async(id:string)=>{await notifee.cancelTriggerNotification(id).catch(()=>undefined);await execute('UPDATE reminders SET enabled=0,updated_at=? WHERE id=?',[new Date().toISOString(),id]);};
export const scheduleDebtReminders=async(debtId:string)=>{const debt=await one<any>('SELECT * FROM debts WHERE id=?',[debtId]);if(!debt)return;const existing=await rows<any>('SELECT id FROM reminders WHERE category=\'debt\' AND entity_id=?',[debtId]);for(const r of existing)await notifee.cancelTriggerNotification(r.id).catch(()=>undefined);await execute('DELETE FROM reminders WHERE category=\'debt\' AND entity_id=?',[debtId]);if(debt.status==='paid'||debt.current_balance<=0)return;const due=new Date(`${debt.due_date}T09:00:00`);for(const days of [30,14,7,3,1,0]){const at=new Date(due);at.setDate(at.getDate()-days);if(at.getTime()<=Date.now())continue;const when=days===0?'today':days===1?'tomorrow':`in ${days} days`;await scheduleLocalReminder({title:'Loan payment reminder',message:`${formatMoney(debt.minimum_payment,debt.currency)} payment to ${debt.lender_name} is due ${when}.`,scheduledAt:at.toISOString(),category:'debt',entityId:debtId});}const overdue=new Date(due);overdue.setDate(overdue.getDate()+1);if(overdue.getTime()>Date.now())await scheduleLocalReminder({title:'Debt payment overdue',message:`Payment to ${debt.lender_name} is overdue. Outstanding: ${formatMoney(debt.current_balance,debt.currency)}.`,scheduledAt:overdue.toISOString(),category:'debt',entityId:debtId});};
export const displayBudgetWarning=async(title:string,body:string)=>{if(!(await categoryAllowed('budget')))return;const today=new Date().toISOString().slice(0,10);const sent=await one<any>("SELECT id FROM notifications WHERE category='budget' AND title=? AND substr(delivered_at,1,10)=? LIMIT 1",[title,today]);if(sent)return;await ensureNotificationChannel();await notifee.displayNotification({title,body,data:{category:'budget'},android:{channelId:FINORA_CHANNEL,importance:AndroidImportance.HIGH,pressAction:{id:'default'}}});const now=new Date().toISOString();await execute('INSERT INTO notifications(id,title,body,category,delivered_at) VALUES(?,?,?,?,?)',[uuid(),title,body,'budget',now]);};
export const reconcileReminders=async()=>{await ensureNotificationChannel();const prefs=await loadPreferences(),allowed=prefs.notificationCategories||{debt:true,budget:true,savings:true,bill:true,custom:true};const enabled=await rows<any>('SELECT * FROM reminders WHERE enabled=1 AND scheduled_at>? ORDER BY scheduled_at LIMIT 50',[new Date().toISOString()]);const existing=new Set(await notifee.getTriggerNotificationIds());for(const id of existing){const r=await one<any>('SELECT category FROM reminders WHERE notification_id=? OR id=?',[id,id]);if(!prefs.notificationEnabled||r&&(allowed as any)[r.category]===false)await notifee.cancelTriggerNotification(id).catch(()=>undefined);}if(!prefs.notificationEnabled)return;for(const r of enabled){if((allowed as any)[r.category]===false||existing.has(r.notification_id||r.id))continue;try{await createTrigger(r.notification_id||r.id,r.title,r.message,r.scheduled_at,r.repeat_frequency)}catch{}}};
export const recordNotificationEvent=async(notification:any)=>{if(!notification?.id)return;const exists=await one<any>('SELECT id FROM notifications WHERE id=?',[notification.id]);if(exists)return;await execute('INSERT INTO notifications(id,title,body,category,delivered_at) VALUES(?,?,?,?,?)',[notification.id,notification.title||'Finora',notification.body||'',notification.data?.category||'reminder',new Date().toISOString()]);};
