jest.mock('../src/database/db',()=>({execute:jest.fn(async()=>({})),one:jest.fn(async()=>undefined),rows:jest.fn(async()=>[]),transaction:jest.fn()}));
jest.mock('../src/services/accountService',()=>({recalculateAccountBalances:jest.fn(async()=>{})}));
jest.mock('../src/services/auditService',()=>({audit:jest.fn(async()=>{})}));
jest.mock('../src/services/budgetService',()=>({evaluateBudgetWarnings:jest.fn(async()=>{})}));
import {execute,one} from '../src/database/db';
import {recalculateAccountBalances} from '../src/services/accountService';
import {evaluateBudgetWarnings} from '../src/services/budgetService';
import {createTransaction,updateTransaction,deleteTransaction} from '../src/services/transactionService';
const mockExecute=execute as jest.Mock;const mockOne=one as jest.Mock;const mockRecalculate=recalculateAccountBalances as jest.Mock;const mockBudget=evaluateBudgetWarnings as jest.Mock;
const base={type:'expense' as const,amount:1500,currency:'NGN',date:'2026-09-25',time:'12:00',description:'Lunch',accountId:'acc-1'};
describe('transaction service',()=>{beforeEach(()=>{jest.clearAllMocks();mockOne.mockResolvedValue(undefined)});test('creates and recalculates',async()=>{await createTransaction(base);expect(mockExecute).toHaveBeenCalledWith(expect.stringContaining('INSERT INTO transactions'),expect.any(Array));expect(mockRecalculate).toHaveBeenCalled();expect(mockBudget).toHaveBeenCalled();});test('edits and recalculates',async()=>{await updateTransaction('tx-1',{...base,amount:1800});expect(mockExecute).toHaveBeenCalledWith(expect.stringContaining('UPDATE transactions'),expect.any(Array));expect(mockRecalculate).toHaveBeenCalled();});test('deletes and recalculates',async()=>{await deleteTransaction('tx-1');expect(mockExecute).toHaveBeenCalledWith('DELETE FROM transactions WHERE id=?',['tx-1']);expect(mockRecalculate).toHaveBeenCalled();});test('rejects invalid transfer',async()=>{await expect(createTransaction({...base,type:'transfer',toAccountId:'acc-1'})).rejects.toThrow(/different destination/i);});});
